- name: "Download Caddy"
  get_url:
    url: "{{ caddy_download_url }}"
    dest: '/tmp/caddy.tar.gz'

- name: "Extract Caddy"
  unarchive:
    src: '/tmp/caddy.tar.gz'
    dest: '/tmp'
    remote_src: yes
    creates: '/tmp/caddy'

- name: "Install Caddy"
  copy:
    src: '/tmp/caddy'
    dest: '/usr/local/bin/caddy'
    owner: root
    group: root
    mode: 0755
    remote_src: yes

