- include: 'users_and_folders.yml'
- include: 'download.yml'

- capabilities:
    path: /usr/local/bin/caddy
    capability: "cap_net_bind_service=+ep"
    state: present
  when: 'caddy_use_capabilities'
  name: "Set capabilities"

- template:
    src: 'caddy.service'
    dest: /etc/systemd/system/caddy.service
    owner: root
    group: root
    mode: 0644
  name: "Copy systemd config"

- template:
    src: 'caddyfile.j2'
    dest: "{{ caddy_caddyfile }}"
    owner: root
    group: root
    mode: 0644
  notify: reload caddy
  when: 'caddy_manage_caddyfile'
  tags: [caddy_config]
  name: "Copy caddyfile"

- systemd:
    daemon_reload: true
    enabled: true
    name: 'caddy.service'
    state: started
  name: "Start/reload systemd"
