- user:
    name: '{{caddy_user}}'
    home: '{{caddy_user_home}}'
    create_home: false
    shell: /usr/sbin/nologin
  when: 'caddy_user != "root"'

- file:
    path: '{{caddy_user_home}}'
    state: directory
    owner: '{{caddy_user}}'
    group: '{{caddy_user}}'
    mode: 0555
  name: 'mkdir caddy_user_home'

- file:
    path: "{{item}}"
    state: directory
    owner: '{{caddy_user}}'
    group: '{{caddy_user}}'
    mode: 0755
  name: 'mkdir caddy_log_dir + config_dir'
  with_items:
    - '{{caddy_log_dir}}'
    - '{{caddy_config_dir}}'

- file:
    path: "{{caddy_log_dir}}/{{item.name}}"
    state: directory
    owner: '{{caddy_user}}'
    group: '{{caddy_user}}'
    mode: 0755
  name: 'mkdir {{item}}'
  with_items: "{{caddy_routings}}"
  tags: [caddy_config]

- file:
    path: /etc/ssl/caddy
    state: directory
    owner: root
    group: '{{caddy_user}}'
    mode: 0770
  name: 'mkdir /etc/ssl/caddy'
